[package]
name = "msgpack-rpc"
version = "0.1.0"
authors = ["Andy Russell <arussell123@gmail.com>"]

[dependencies]
env_logger = "0.3"
mioco = "^0.8"
rmp = "^0.8"
rmpv = "0.4"
rmp-serde = "0.13"
serde = "*"
